//EXTERNAL LIBRARIES
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//STYLES
import "./globals.css";

//PROVIDERS
import { Provider } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Main = ({ children }: { children: React.ReactNode }) => {
  return children;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Provider>
          <Main>{children}</Main>
        </Provider>
      </body>
    </html>
  );
}
